django_project/api/urls.py
from api.models import CourseResource, CategoryResource
from tastypie.api import Api
from django.urls import path, include

api = Api(api_name='v1')
api.register(CourseResource())
api.register(CategoryResource())

#For POST, DELETE add header
#Key: Authorization
#Value: ApiKey Walker:das12ewd121dqw


urlpatterns = [
    path('', include(api.urls), name= 'index')
]

django_project/base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('api/', include('api.urls')),
]

django_project/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name= 'single_course'),
]

django_project/api/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        authentication = CustomAuthentication()
        authorization = Authorization()
        excludes = ['reviews_qty', 'created_at']


    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category
        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()

django_project/shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

django_project/api/views.py
from django.shortcuts import render

# Create your views here.

django_project/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course


def index(response):
    courses = Course.objects.all()
    return render(response, 'shop/courses.html', {'courses': courses})
    # ''.join([str(i) + '<br>' for i in courses])


def single_course(request, course_id):
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'shop/single_course.html', {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404()
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

django_project/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{%block title%}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href= {% url "shop:index" %} class="navbar-brand btn btn-outline-dark btn-sm">Courses Shop</a>
            <span class="navbar-text">
                <a href="/admin/" class="btn btn-outline-dark btn-sm" target="_blank">Admin</a>
                <a href="/api/v1/" class="btn btn-outline-dark btn-sm" target="_blank">API</a>
            </span>

        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        .btn:hover {
            transform: scale(1.05);
            transition: all 0.3s ease;
        }
        .card:hover {
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);
            transition: all 0.3s ease;
        }

        .btn-buy:hover {
            transform: none;
        }
    </style>
</head>






django_project/templates/shop/courses.html
{% extends 'base.html' %}

{% block title %}All Courses{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {%for course in courses%}
        <tr>
            <td><a href={% url "shop:single_course" course.id %}>{{course.title}}</a>
            </td>
            <td>{{course.category}}</td>
            <td>{{course.price}}</td>
            <td>{{course.students_qty}}</td>
            <td><a href="{{ buy_url }}" class="btn btn-primary">Buy</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

django_project/templates/shop/single_course.html
{% extends 'base.html' %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<div class="mt-5 card">
  <h1 class="card-header">
      {{course.title}}
  </h1>
  <div class="card-body">
    <h5 class="card-title">{{course.category}}</h5>
    <p class="card-text">Price: {{course.price}}
    <a href="{{ buy_url }}" class="btn btn-primary btn-buy">Buy</a></p>
      <p1 class="card-text"> Students quantity: {{course.students_qty}}</p1>
  </div>
</div>

{% endblock %}